### ISSUE TITLE
Failure message on successful -promote subcommand

### ISSUE THREAD

**Issue by Bearzooka** [univ-of-utah-marriott-library-apple/jctl#54]
After running the `promote` subcommand for a policy (e.g. GitHub Desktop) as a result I first get the picker, and then once a selection is made, the following:
```
{'package': [{'action': 'Install',
              'feu': 'false',
              'fut': 'false',
              'name': 'GitHubDesktop-M1-3.1.1.pkg'}],
 'size': '1'}
Sub command failed
```

What is puzzling here is that the promotion was in fact successful and my policy is updated, so the `Sub command failed` part is wrong or not clear.

Thanks.

**Comment by magnusviri** [comment]
@Bearzooka pkgctl has issues. I'm hoping to not get distracted but to work on it today.

**Comment by magnusviri** [comment]
I just fixed this with a new release, 1.1.18.

**Comment by magnusviri** [comment]
I've released a new version. Can you see if the problem is fixed now?

**Comment by Bearzooka** [comment]
Hi @magnusviri, thanks for the efforts!

I tested it (also including the lines you committed to fix #57) and I still get the error saying `Sub command failed`, and just like before, the policy is in fact updated, so the error message is not necessary.

**Comment by magnusviri** [comment]
Hey @Bearzooka, we finally released a major update. Can you update and try this again?

**Comment by Bearzooka** [comment]
Hey @magnusviri, unfortunately I'm no longer able to test, as my current organization doesn't allow third party API tools to interact with Jamf. Thanks for the great efforts tho!

**Comment by magnusviri** [comment]
Sounds good. Thanks!
